# Generated by Django 5.0.6 on 2024-06-08 12:38

import typeid_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    typeid_field.fields.TypeidField(
                        default=typeid_field.fields.TypeidField.typeid,
                        editable=False,
                        max_length=27,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "override",
                    typeid_field.fields.TypeidField(
                        default=typeid_field.fields.TypeidField.typeid, max_length=30
                    ),
                ),
            ],
        ),
    ]
