# Generated by Django 4.2.6 on 2023-10-29 21:02

from django.db import migrations
import typeid_field.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    typeid_field.fields.TypeidField(
                        default=typeid_field.fields.TypeidField.typeid,
                        editable=False,
                        max_length=21,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "override",
                    typeid_field.fields.TypeidField(
                        default=typeid_field.fields.TypeidField.typeid, max_length=2
                    ),
                ),
            ],
        ),
    ]
