# Generated by Django 5.0.6 on 2024-06-08 14:29

import typeid_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="override",
            field=typeid_field.fields.TypeidField(max_length=30, prefix="pfx"),
        ),
    ]
